### ISSUE TITLE
ida7.0 api

### ISSUE THREAD

**Issue by grokeus** [sibears/IDAGolangHelper#5]
Need to rewrite using actual IDA api

**Comment by silascutler** [comment]
I've started some testing on IDA 7.2 and have some notes that may be useful:

- IDAGolangHelper works relatively well -  when run as a stand-alone script
- When installed as a plugin, the script will attempt to run twice (first time, `idc.BeginEA` returns `0xffffffffL`)
- Running `Parse types by moduledata` throws the following error:
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/opt/ida-7.2/python/ida_kernwin.py", line 5963, in helper_cb
    r = self.handler(button_code)
  File "/home/re/.idapro/plugins/go_entry.py", line 69, in OnButton5
    GO_SETTINGS.typesModuleData(typ)
  File "/home/re/.idapro/plugins/GO_Utils/__init__.py", line 120, in typesModuleData
    for i in self.processor:
  File "/home/re/.idapro/plugins/GO_Utils/Types.py", line 534, in next
    return self.handle_offset(value)
  File "/home/re/.idapro/plugins/GO_Utils/Types.py", line 325, in handle_offset
    kind_name = self.getKindEnumName(offset)
  File "/home/re/.idapro/plugins/GO_Utils/Types.py", line 309, in getKindEnumName
    return self.settings.typer.standardEnums[0][1][kind]
IndexError: list index out of range
```

**Comment by grokeus** [comment]
Hi!
Thanks for the feedback!
Actually my code was written as standalone script for now.
Did you make some modifications before loading as plugin?

also, do you know which go version was used to compile your binary? I didn't make updates since go1.10 (no need to reverse golang frequently for me now)
But if needed I guess I can find some time to make fixes for newer golang version :)
